set -g default-terminal "tmux-256color"
set-option -ga terminal-features ",xterm-256color:RGB"
set-option -g allow-passthrough on
set -g allow-rename on
set -g set-titles on
set -s escape-time 0
set -g base-index 1
