import = [
    "~/.config/alacritty/themes/tokyonight_moon.toml"
]

[font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
dynamic_title = true

[[hints.enabled]]
binding = { key = "E", mods = "Control | Shift" }
command = "xdg-open"
hyperlinks = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|go‐pher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
mouse.enabled = true
