return {}
-- {
--   {
--     "GCBallesteros/jupytext.nvim",
--     opts = {
--       style = "markdown",
--       output_extension = "md",
--       force_ft = "markdown",
--     },
--   },
--   {
--     "benlubas/molten-nvim",
--     build = ":UpdateRemotePlugins",
--     cmd = { "MoltenInit" },
--     init = function()
--       -- these are examples, not defaults. Please see the readme
--       vim.g.molten_image_provider = "image.nvim"
--       vim.g.molten_cover_empty_lines = true
--       vim.g.molten_output_virt_lines = true
--       vim.g.molten_auto_open_output = false
--       vim.g.molten_wrap_output = true
--       vim.g.molten_virt_text_output = false
--       vim.g.molten_output_win_max_height = 20
--     end,
--     keys = {
--       { "<leader>ji", "<Cmd>MoltenInit<CR>", desc = "Initialize Molten" },
--       { "<leader>jl", "<Cmd>MoltenEvaluateLine<CR>", desc = "Molten evaluate line" },
--       { "<leader>jo", "<Cmd>MoltenEvaluateOperator<CR>", desc = "Molten evaluate line" },
--       { "<leader>je", "<Cmd>noautocmd MoltenEnterOutput<CR>", desc = "Molten enter output" },
--       { "<leader>jq", "<Cmd>MoltenHideOutput<CR>", desc = "Molten enter output" },
--       { "<leader>j", "<Cmd>MoltenEvaluateVisual<CR>", mode = "v", desc = "Molten evaluate selection" },
--     },
--   },
--   {
--     "jmbuhr/otter.nvim",
--     dev = true,
--     opts = function()
--       return {
--         lsp = {
--           -- diagnostic_update_events = { "BufWritePost" },
--           diagnostic_update_events = { "BufWritePost", "InsertLeave", "TextChanged" },
--         },
--         buffers = {
--           set_filetype = true,
--           write_to_disk = true,
--         },
--         debug = false,
--       }
--     end,
--     keys = {
--       { "<leader>ja", function() require("otter").activate() end, desc = "Activate otter" },
--       { "<leader>jd", function() require("otter").deactivate() end, desc = "Deactivate otter" }
--     },
--   },
-- }
